version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /opt/docker.hub/compose/example:/code
    depends_on:
      - redis
    environment:
      - constraint:node==ceph1
  redis:
    image: redis
